- name: get info on docker host
  become: true
  docker_host_info:
  register: result_docker_host_info

- name: leave swarm cluster if not the same cluster_id
  become: true
  docker_swarm:
    state: absent
  when: >-
    'Swarm' in result_docker_host_info.host_info
    and 'Cluster' in result_docker_host_info.host_info.Swarm
    and result_docker_host_info.host_info.Swarm.Cluster.ID != swarm_cluster_id

- name: add node to cluster
  become: true
  docker_swarm:
    state: join
    advertise_addr: "{{ docker_advertise_address | default(ansible_default_ipv4.address) }}"
    join_token: "{{ join_token }}"
    remote_addrs: "{{ swarm_remote_addresses }}"
