- name: get os distribution
  set_fact:
    is_debian_based: "{{ ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' }}"
    is_rhel_based: "{{ ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' }}"
    is_amazon_based: "{{ ansible_distribution == 'Amazon' }}"
    is_python2: "{{ ansible_python_version.startswith('2.') }}"

- name: removing non needed python modules
  become: "{{ is_python2 }}"
  pip:
    name:
      - docker-py
    state: absent

- name: installing needed python modules
  become: "{{ is_python2 }}"
  pip:
    name:
      - docker
    state: present

- name: get info on docker host
  become: true
  docker_host_info:
  ignore_errors: true
  register: docker_info

- set_fact:
    should_install_docker: "{{ docker_info.failed == True or docker_info.host_info.ServerVersion != docker_version }}"
