- name: gather service facts
  become: true
  service_facts:

- include_tasks: stop-daemon.yml
  when: '"docker.service" in services'

- name: remove old versions
  become: yes
  command: >
    yum remove -y
    docker
    docker-client
    docker-client-latest
    docker-common
    docker-latest
    docker-latest-logrotate
    docker-logrotate
    docker-engine

- name: "installing docker"
  become: yes
  command: amazon-linux-extras install -y docker
  register: docker_installation

- include_tasks: restart-daemon.yml
  when: 'docker_installation.changed == true'
