- name: gather service facts
  become: true
  service_facts:

- include_tasks: stop-daemon.yml
  when: '"docker.service" in services'

- name: remove old versions
  become: true
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: install package to allow apt to use repository over https
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: add docker's official gpg key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: setup stable repository
  become: true
  apt_repository:
    repo:  "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: "installing docker {{ docker_version }}"
  become: true
  apt:
    name:
      - "docker-ce={{ docker_version }}"
      - "docker-ce-cli={{ docker_version }}"
      - containerd.io
    state: present
    update_cache: true
  register: docker_installation

- include_tasks: restart-daemon.yml
  when: 'docker_installation.changed == true'
